export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-black text-white bg-[length:200%_200%] animate-gradient">{children}</body>
    </html>
  )
}

